/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DreamCard: typeof import('./components/diary/DreamCard.vue')['default']
    GoodThingsCard: typeof import('./components/diary/GoodThingsCard.vue')['default']
    KnowledgeCard: typeof import('./components/diary/KnowledgeCard.vue')['default']
    MealCard: typeof import('./components/diary/MealCard.vue')['default']
    ReflectionCard: typeof import('./components/diary/ReflectionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SleepCard: typeof import('./components/diary/SleepCard.vue')['default']
    TimeGrid: typeof import('./components/TimeGrid/TimeGrid.vue')['default']
    TomorrowCard: typeof import('./components/diary/TomorrowCard.vue')['default']
    WorkStudyCard: typeof import('./components/diary/WorkStudyCard.vue')['default']
  }
}
